name: flutter_orm
description: An annotation-based ORM for Flutter inspired by the Room persistence library. This library is based on sqflite and wraps it for better APIs.
version: 0.0.4
homepage: https://github.com/salehyarahmadi/flutter_orm

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:


dev_dependencies:
  lints: ^2.0.0