name: flutter_orm_generator
description: A generator for flutter_orm
version: 0.0.3
homepage: https://github.com/salehyarahmadi/flutter_orm

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  analyzer: 5.13.0
  source_gen: ^1.3.2
  build: ^2.4.0
  flutter_orm: ^0.0.5
#    path: ../flutter_orm


dev_dependencies:
  lints: ^2.0.0
